/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#faf8ff",
        "surface-dim": "#d2d8fb",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f2ff",
        "surface-container": "#ebedff",
        "surface-container-high": "#e4e7ff",
        "surface-container-highest": "#dce1ff",
        "on-surface": "#131a34",
        "on-surface-variant": "#434656",
        "inverse-surface": "#282f4a",
        "inverse-on-surface": "#eff0ff",
        "outline": "#737687",
        "outline-variant": "#c3c5d8",
        "surface-tint": "#004cec",
        "primary": "#003fc8",
        "on-primary": "#ffffff",
        "primary-container": "#1a56f5",
        "on-primary-container": "#e1e4ff",
        "inverse-primary": "#b7c4ff",
        "secondary": "#5a5e6c",
        "on-secondary": "#ffffff",
        "secondary-container": "#dcdfef",
        "on-secondary-container": "#5f6270",
        "tertiary": "#005b3e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#007652",
        "on-tertiary-container": "#89fcc7",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b7c4ff",
        "on-primary-fixed": "#001551",
        "on-primary-fixed-variant": "#0039b5",
        "secondary-fixed": "#dfe2f2",
        "secondary-fixed-dim": "#c3c6d6",
        "on-secondary-fixed": "#171b27",
        "on-secondary-fixed-variant": "#434653",
        "tertiary-fixed": "#85f8c4",
        "tertiary-fixed-dim": "#68dba9",
        "on-tertiary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#005137",
        "background": "#faf8ff",
        "on-background": "#131a34",
        "surface-variant": "#dce1ff"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "1.5rem",
        "3xl": "24px",
        "full": "9999px"
      },
      fontFamily: {
        "body": ["Manrope", "sans-serif"],
        "headline": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      boxShadow: {
        'premium': '0 2px 4px rgba(0, 0, 0, 0.05)',
        'glass': '0 8px 32px -8px rgba(31, 38, 135, 0.37)',
      },
      backdropBlur: {
        'glass': 'blur(4px)',
      }
    },
  },
  darkMode: 'class',
  plugins: [],
}
