/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#222b47",
        "on-secondary-fixed": "#40009b",
        "on-tertiary-fixed": "#00163b",
        "on-primary-fixed-variant": "#005762",
        "secondary": "#ac8aff",
        "primary-dim": "#00d4ec",
        "surface-container-high": "#171f36",
        "secondary-container": "#5516be",
        "surface-dim": "#070d1f",
        "primary-container": "#00e3fd",
        "error-container": "#9f0519",
        "outline": "#6f758b",
        "on-surface": "#dfe4fe",
        "surface-variant": "#1c253e",
        "outline-variant": "#41475b",
        "tertiary-dim": "#699cff",
        "secondary-fixed-dim": "#ceb9ff",
        "surface-container": "#11192e",
        "on-secondary-fixed-variant": "#5f28c8",
        "background": "#070d1f",
        "secondary-dim": "#8455ef",
        "inverse-primary": "#006976",
        "primary-fixed-dim": "#00d4ec",
        "on-secondary-container": "#d9c8ff",
        "primary-fixed": "#00e3fd",
        "tertiary": "#699cff",
        "on-tertiary-fixed-variant": "#00377b",
        "on-tertiary": "#001e4a",
        "secondary-fixed": "#dac9ff",
        "on-surface-variant": "#a5aac2",
        "error-dim": "#d7383b",
        "primary": "#81ecff",
        "tertiary-fixed-dim": "#73a2ff",
        "on-error": "#490006",
        "inverse-surface": "#faf8ff",
        "error": "#ff716c",
        "on-primary": "#005762",
        "on-primary-fixed": "#003840",
        "surface-tint": "#81ecff",
        "on-tertiary-container": "#000311",
        "on-error-container": "#ffa8a3",
        "surface-container-highest": "#1c253e",
        "tertiary-fixed": "#8ab0ff",
        "surface-container-low": "#0c1326",
        "on-secondary": "#280067",
        "surface-container-lowest": "#000000",
        "surface": "#070d1f",
        "inverse-on-surface": "#4f5469",
        "on-primary-container": "#004d57",
        "on-background": "#dfe4fe",
        "tertiary-container": "#4388fd"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "1rem",
        "3xl": "24px",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      boxShadow: {
        'premium': '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
        'glass': '0 8px 32px -8px rgba(31, 38, 135, 0.37)',
      },
      backdropBlur: {
        'glass': 'blur(4px)',
      }
    },
  },
  darkMode: 'class',
  plugins: [],
}
